### ISSUE TITLE
Rosserial Sync Error for Arduino UNO car.ino

### ISSUE THREAD

**Issue by sohartma** [RiccardoGiubilato/ros_autonomous_car#2]
I'm getting this error:
Unable to sync with device; possible link problem or link software version mismatch such as hydro rosserial_python with groovy Arduino

I don't have different versions though. Maybe the message size is too big for the Arduino UNO?

**Comment by sohartma** [comment]
Solved this one by commenting every line of the MPU out of the sketch. However the sonar topics are empty. No data is sent...

**Comment by RiccardoGiubilato** [comment]
Please check that values before line 465, excluding yaw, are valid. 
Does the code execution reach the publish command?

**Comment by RiccardoGiubilato** [comment]
Problem might be with the size of SRAM
